# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from navigation/GeoPointRange.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GeoPointRange(genpy.Message):
  _md5sum = "8a4b85d7b91a11f0867d2e73a2c8f009"
  _type = "navigation/GeoPointRange"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 min_latitude
float64 max_latitude
float64 min_longitude
float64 max_longitude
float64 min_altitude
float64 max_altitude 
"""
  __slots__ = ['min_latitude','max_latitude','min_longitude','max_longitude','min_altitude','max_altitude']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       min_latitude,max_latitude,min_longitude,max_longitude,min_altitude,max_altitude

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GeoPointRange, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.min_latitude is None:
        self.min_latitude = 0.
      if self.max_latitude is None:
        self.max_latitude = 0.
      if self.min_longitude is None:
        self.min_longitude = 0.
      if self.max_longitude is None:
        self.max_longitude = 0.
      if self.min_altitude is None:
        self.min_altitude = 0.
      if self.max_altitude is None:
        self.max_altitude = 0.
    else:
      self.min_latitude = 0.
      self.max_latitude = 0.
      self.min_longitude = 0.
      self.max_longitude = 0.
      self.min_altitude = 0.
      self.max_altitude = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.min_latitude, _x.max_latitude, _x.min_longitude, _x.max_longitude, _x.min_altitude, _x.max_altitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.min_latitude, _x.max_latitude, _x.min_longitude, _x.max_longitude, _x.min_altitude, _x.max_altitude,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.min_latitude, _x.max_latitude, _x.min_longitude, _x.max_longitude, _x.min_altitude, _x.max_altitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.min_latitude, _x.max_latitude, _x.min_longitude, _x.max_longitude, _x.min_altitude, _x.max_altitude,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
