// Generated by gencpp from file navigation/Compass.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_COMPASS_H
#define NAVIGATION_MESSAGE_COMPASS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct Compass_
{
  typedef Compass_<ContainerAllocator> Type;

  Compass_()
    : heading(0.0)  {
    }
  Compass_(const ContainerAllocator& _alloc)
    : heading(0.0)  {
  (void)_alloc;
    }



   typedef double _heading_type;
  _heading_type heading;





  typedef boost::shared_ptr< ::navigation::Compass_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::Compass_<ContainerAllocator> const> ConstPtr;

}; // struct Compass_

typedef ::navigation::Compass_<std::allocator<void> > Compass;

typedef boost::shared_ptr< ::navigation::Compass > CompassPtr;
typedef boost::shared_ptr< ::navigation::Compass const> CompassConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::Compass_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::Compass_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::Compass_<ContainerAllocator1> & lhs, const ::navigation::Compass_<ContainerAllocator2> & rhs)
{
  return lhs.heading == rhs.heading;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::Compass_<ContainerAllocator1> & lhs, const ::navigation::Compass_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::navigation::Compass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::Compass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::Compass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::Compass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::Compass_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::Compass_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::Compass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9635d0d9f52c085a5bcd934107785851";
  }

  static const char* value(const ::navigation::Compass_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9635d0d9f52c085aULL;
  static const uint64_t static_value2 = 0x5bcd934107785851ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::Compass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/Compass";
  }

  static const char* value(const ::navigation::Compass_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::Compass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 heading\n"
;
  }

  static const char* value(const ::navigation::Compass_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::Compass_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Compass_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::Compass_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::Compass_<ContainerAllocator>& v)
  {
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_COMPASS_H
