// Generated by gencpp from file navigation/PropInProgress.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_PROPINPROGRESS_H
#define NAVIGATION_MESSAGE_PROPINPROGRESS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geographic_msgs/GeoPoint.h>

namespace navigation
{
template <class ContainerAllocator>
struct PropInProgress_
{
  typedef PropInProgress_<ContainerAllocator> Type;

  PropInProgress_()
    : prop_type()
    , theta_1(0.0)
    , theta_2(0.0)
    , closest_pnt_dist(0.0)
    , closest_pnt_angle(0.0)
    , prop_coords()  {
    }
  PropInProgress_(const ContainerAllocator& _alloc)
    : prop_type(_alloc)
    , theta_1(0.0)
    , theta_2(0.0)
    , closest_pnt_dist(0.0)
    , closest_pnt_angle(0.0)
    , prop_coords(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _prop_type_type;
  _prop_type_type prop_type;

   typedef float _theta_1_type;
  _theta_1_type theta_1;

   typedef float _theta_2_type;
  _theta_2_type theta_2;

   typedef float _closest_pnt_dist_type;
  _closest_pnt_dist_type closest_pnt_dist;

   typedef float _closest_pnt_angle_type;
  _closest_pnt_angle_type closest_pnt_angle;

   typedef  ::geographic_msgs::GeoPoint_<ContainerAllocator>  _prop_coords_type;
  _prop_coords_type prop_coords;





  typedef boost::shared_ptr< ::navigation::PropInProgress_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::PropInProgress_<ContainerAllocator> const> ConstPtr;

}; // struct PropInProgress_

typedef ::navigation::PropInProgress_<std::allocator<void> > PropInProgress;

typedef boost::shared_ptr< ::navigation::PropInProgress > PropInProgressPtr;
typedef boost::shared_ptr< ::navigation::PropInProgress const> PropInProgressConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::PropInProgress_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::PropInProgress_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::PropInProgress_<ContainerAllocator1> & lhs, const ::navigation::PropInProgress_<ContainerAllocator2> & rhs)
{
  return lhs.prop_type == rhs.prop_type &&
    lhs.theta_1 == rhs.theta_1 &&
    lhs.theta_2 == rhs.theta_2 &&
    lhs.closest_pnt_dist == rhs.closest_pnt_dist &&
    lhs.closest_pnt_angle == rhs.closest_pnt_angle &&
    lhs.prop_coords == rhs.prop_coords;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::PropInProgress_<ContainerAllocator1> & lhs, const ::navigation::PropInProgress_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::navigation::PropInProgress_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::PropInProgress_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::PropInProgress_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::PropInProgress_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::PropInProgress_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::PropInProgress_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::PropInProgress_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6c33540b8c16df4f5cfffc348148909";
  }

  static const char* value(const ::navigation::PropInProgress_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6c33540b8c16df4ULL;
  static const uint64_t static_value2 = 0xf5cfffc348148909ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::PropInProgress_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/PropInProgress";
  }

  static const char* value(const ::navigation::PropInProgress_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::PropInProgress_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string prop_type\n"
"float32 theta_1\n"
"float32 theta_2\n"
"float32 closest_pnt_dist\n"
"float32 closest_pnt_angle\n"
"geographic_msgs/GeoPoint prop_coords\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geographic_msgs/GeoPoint\n"
"# Geographic point, using the WGS 84 reference ellipsoid.\n"
"\n"
"# Latitude [degrees]. Positive is north of equator; negative is south\n"
"# (-90 <= latitude <= +90).\n"
"float64 latitude\n"
"\n"
"# Longitude [degrees]. Positive is east of prime meridian; negative is\n"
"# west (-180 <= longitude <= +180). At the poles, latitude is -90 or\n"
"# +90, and longitude is irrelevant, but must be in range.\n"
"float64 longitude\n"
"\n"
"# Altitude [m]. Positive is above the WGS 84 ellipsoid (NaN if unspecified).\n"
"float64 altitude\n"
;
  }

  static const char* value(const ::navigation::PropInProgress_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::PropInProgress_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.prop_type);
      stream.next(m.theta_1);
      stream.next(m.theta_2);
      stream.next(m.closest_pnt_dist);
      stream.next(m.closest_pnt_angle);
      stream.next(m.prop_coords);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PropInProgress_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::PropInProgress_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::PropInProgress_<ContainerAllocator>& v)
  {
    s << indent << "prop_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.prop_type);
    s << indent << "theta_1: ";
    Printer<float>::stream(s, indent + "  ", v.theta_1);
    s << indent << "theta_2: ";
    Printer<float>::stream(s, indent + "  ", v.theta_2);
    s << indent << "closest_pnt_dist: ";
    Printer<float>::stream(s, indent + "  ", v.closest_pnt_dist);
    s << indent << "closest_pnt_angle: ";
    Printer<float>::stream(s, indent + "  ", v.closest_pnt_angle);
    s << indent << "prop_coords: ";
    s << std::endl;
    Printer< ::geographic_msgs::GeoPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.prop_coords);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_PROPINPROGRESS_H
